services:
  streamlit-app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        # Define required args for the container
        GUARDRAILS_TOKEN: ${GUARDRAILS_TOKEN}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GUARDRAILS_TOKEN=${GUARDRAILS_TOKEN}
      - COLLECTOR_ENDPOINT=http://phoenix:6006/v1/traces
    # Map port 8080 of the container to port 8080 on the host
    # This allows the Streamlit app to be accessed from the host machine
    ports:
      - "8080:8080"
    # Mount volumes for live code updating
    # This maps the src directory and .streamlit configuration
    # from your host to the container
    volumes:
      - ./src:/app/src
      - ./.streamlit:/app/.streamlit
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://0.0.0.0:8080/healthz"]
      interval: 3s
      timeout: 1s
      retries: 3
    depends_on:
      - redis
      - phoenix
  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"  # Expose port 6006 for the UI and OTLP HTTP collector
      - "4317:4317"  # Expose port 4317 for OTLP gRPC collector
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
